version: '3.9'
services:
 php:
   image: php:pami
   build:
     dockerfile: php.Dockerfile
   environment:
    # EXTERNAL CONNECTIONS
    - ASTERISK_HOST
    - ASTERISK_PORT
    - ASTERISK_USER
    - ASTERISK_PASS
   volumes:
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    - ./:/app